### ISSUE TITLE
FacebookManager permission options problem.

### ISSUE THREAD

**Issue by luochuanyuewu** [FlipWebApps/GameFramework#10]
The necessary steps to use Facebook sdk are all ok, i also built the fb sdk example secene and run on android perfectly.
then i try fb manager component, my android game will stop running immediately. after many tries,
i found what is the problem.
![image](https://cloud.githubusercontent.com/assets/9363799/17580338/7a6bbd12-5fd0-11e6-9885-9290d8b7b3c7.png)
those settings works, my game will not crash.
if i choose permission optional or required, my android game will crash whenever i click the login button.

Unity version:5.4.1f3
GameFramw version: latest github version.
Facebook SDK: 7.8

**Comment by FlipWebApps** [comment]
Permissions should have according to the Facebook documentation, but I will try a new android build with the versions you posted.

Can you try enabling just email permission and see if that still causes a crash?

**Comment by luochuanyuewu** [comment]
When i only enable email, it was succeed. also, after i watching unity ads video, the coins will not change immediately again.

**Comment by FlipWebApps** [comment]
Hi. Can you also try with the other two permissions - just enable them one a time so I can know if it is a particular permission causing the problem? One possibility is that this is linked to approval of the app on the Facebook side although if so should be handled a bit more gracefully.

On the other issue, coins are updated on the Player if the user watched the whole ad:

                                GameManager.Instance.GetPlayer().Coins += coins;
                                GameManager.Instance.GetPlayer().UpdatePlayerPrefs();
                                PreferencesFactory.Save();

Can you see if this is updated in the cheat functions window? If needed I can add more options e.g. always reward even if they don't watch the whole ad.

Thanks,
Mark

**Comment by luochuanyuewu** [comment]
Request Publish Actions Permission is the bad guy.  :)

**Comment by FlipWebApps** [comment]
Thanks. I will look into it. Did you get the ad coins thing working? I did a test just within the editor and it updated fine for me..

**Comment by luochuanyuewu** [comment]
ad conis things are ok, i just attached a animator component without actual animator controller, so it block the coin update processs.

**Comment by FlipWebApps** [comment]
So that permission will need to use FB.LogInWithPublishPermissions method as described on this page: https://developers.facebook.com/docs/unity/reference/current/FB.LogInWithPublishPermissions

They also mention that best practice is "you should only ask for publish permissions once a person is ready to post something from your app and not during the initial login" I will keep the option as it might be a game defers login until such time, but will add a separate condition to calls the above method when publish_actions is requested.

**Comment by luochuanyuewu** [comment]
Thanks, I see.
