### ISSUE TITLE
Localisation file priority problem.

### ISSUE THREAD

**Issue by luochuanyuewu** [FlipWebApps/GameFramework#11]
I set a simple localisation test, put a localisation file into my Resources folder, i will not be loaded or appended.
after some debugging, i found that the system loaded wrong localisation file located at FlipWebApps\GameFrameworkTutorials\Localisation\Resources\Localisation.csv(not my own one).When i deleted this localisation file, problem is gone.

**Comment by FlipWebApps** [comment]
Thanks. I have fixed ready for the next release by creating a subfolder "FlipWebApps\GameFrameworkTutorials\Localisation\LocalisationTutorial" and moving the Localisation.csv file over to that.
