### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aneroin** [FlipWebApps/GameFramework#12]
Sorry for such generic title =) 
I'm software engineer student from Ukraine, and in our Object Oriented Programming course we are forced to make a contribution to some open source project. Since I'm also working in small gamedev team and we are using Unity, I'm interested to help you if you have some features that you wanna implement.
I'm writing in **C#**, know **OOP** and **SOLID** principles, already worked with **Unity3D**.
So I'd like to find a conclusion with you and make my contribution. 

_you can also contact me via email "halileo@ukr.net"_

> sorry for english, still learning

**Comment by FlipWebApps** [comment]
Thanks for getting in contact. Sent you a mail...
