### ISSUE TITLE
Use ScriptableObjects to allow GameItem Extensions

### ISSUE THREAD

**Issue by FlipWebApps** [FlipWebApps/GameFramework#13]
Currently you can add extra information to a GameItem (Level, World, Character, ... using either a json resources file and / or creating a subclass).  One improvement would be to offer the option of loading a ScriptableObject in the same way json files are loaded that would allow for configuration through the editor and also adding additional code.

Proposed Tasks:

- Create a new GameItemExtension class that inherits from ScriptableObject. This should also have public variables for Name, Description, ValueToUnlock that it set can be used for overriding default values as is done with the json file.
- Add a GameItemExtension property to GameItem and try setting this in GameItem when loading from resources as is done with the json file (in LoadLevelData()).
- Add a new GameItem method GetExtension<T>() that trys converting the scriptable object to the specified type and returns it.

**Comment by aneroin** [comment]
ok, I did it for now, but it still needs further cleanup I think. 

Main question now: how should i handle when to load json and when to search for GameItemExtension? Should it be like "try to find json data, if there none then try to find scriptable object data"?

**Comment by FlipWebApps** [comment]
Excellent. I think that it could try and load both as the overhead shouldn't be that high...

**Comment by aneroin** [comment]
hope i did it right, review please GameItemExtension branch

**Comment by FlipWebApps** [comment]
Hi. Took a quick first look and this looks great. I will try out the change a bit more during the next couple of days and get back with any comments.

**Comment by FlipWebApps** [comment]
I have played around with the changes and everything works just like I had hoped :+1: 

I have a couple of bits that I will add so that there are GameItem extensions specific to some of the other GameItem based classes such as Level, Player etc. Once those are ready then I will merge into the main brance. Excellent work!

**Comment by FlipWebApps** [comment]
Made a couple of small updates and merged with the main branch for inclusion in the next release.

Many thanks again for your help on this.

**Comment by aneroin** [comment]
sorry, i were busy. 
see you already added specific extensions, well, i glad it is working. 

i'll look on next issue and on ukrainian locals in in this or next week. 

also I have some idea to implement achievement system based on reflections. Would give it a try and look at performance. 

23 вересня 2016, 11:27:45, від Flip Web Apps < notifications@github.com >: 

Made a couple of small updates and merged with the main branch for inclusion in the next release. Many thanks again for your help on this. —
