### ISSUE TITLE
Invalid World Unlock Coins Value

### ISSUE THREAD

**Issue by huthaifa-abd** [FlipWebApps/GameFramework#18]
Thank you for the amazing Framework , 
There is one small issue that i encounter using the framework which is that my worlds are getting the same coins value as my levels and they are ignoring the set value in game manager inspector 

I had to change the following line to get the desired result 

File : GameManager.cs
Line : 567 
From : Worlds.LoadDefaultItems(1, NumberOfAutoCreatedWorlds, **CoinsToUnlockLevels**, LoadWorldDatafromResources);

To : 
Worlds.LoadDefaultItems(1, NumberOfAutoCreatedWorlds, **CoinsToUnlockWorlds**, LoadWorldDatafromResources);

Please close this issue if this was intended for some reason , if not a small fix will help lot of other developers using your amazing framework , 

Keep it up , 

Regards

**Comment by FlipWebApps** [comment]
Hi,

Thanks for pointing that out. It was indeed an error. I have fixed this here in github and it will be in the next asset store release also.

Regards,
Mark
