### ISSUE TITLE
Unity compilation error

### ISSUE THREAD

**Issue by TechnoBuddhist** [FlipWebApps/GameFramework#19]
Thank you for the effort that's gone into this I hope to understand it better and use it on my next project, hopefully add or suggest if I can!

Pulled from latest master at 14:00 7 Nov 2016

Unity compilation error :
`Assets/Scripts/GameStructure/GameManager.cs(25,19): error CS0234: The type or namespace name 'BeautifulTransitions' does not exist in the namespace 'FlipWebApps'. Are you missing an assembly reference?`

Line 25 - `using FlipWebApps.BeautifulTransitions.Scripts.Transitions.Components;`
Simply commenting out solves the issue! 

FYI - compiling in Monodev 5.9.6 on Win10 64bit gives 23 errors but I always use Unity for compilation.

UPDATE 
I've just noticed the conditional `#if BEAUTIFUL_TRANSITIONS` in GameManager.cs
Moving the offending line solves the issue!

```
#if BEAUTIFUL_TRANSITIONS
using FlipWebApps.BeautifulTransitions.Scripts.Transitions.Components;
using FlipWebApps.BeautifulTransitions.Scripts.Transitions;
#endif
```

I assume this is the fix!?

**Comment by FlipWebApps** [comment]
Hi TechnoBuddhist,

Thanks for reporting this. I had added some bits towards the next release and not actually tested in a standalone install without some of the updated extras added. I have updated with a fix that will solve the compilation issue. 

The safest way is usually to take one of the tagged releases or the release builds from the Unity asset store. Up until now I have typically worked out of the main branch, but will review this practice given that the project is gaining in popularity.

Regards,
Mark
