### ISSUE TITLE
[Disscuss] Dynamic collectibles

### ISSUE THREAD

**Issue by rubengc** [FlipWebApps/GameFramework#20]
Much games have 2 common collectibles, coins and gems

Coins are the most common and easy to find in game, gems are a rare collectible and in much games you need to purchase this collectible to get it (or showing adds)

I have two proposals to solve this issue
1 - Add gems using same procediments as coins actually
2 - Add support for dynamic count of collectibles

Adding dynamic collectibles adds a lot of new features that could be used to improve user experience in our game, my idea about this is:

1 - Initially Game Framework has two collectibles, points and coins

2 - New methods to get/set this collectibles could be:
- AddCoins(int coins) -> Collect(string collectible, int quantity, int playerNumber = 0), Example:
AddCoins(10) -> Collect('Coin', 10)
AddPoints(10) -> Collect('Point', 10)
- RemoveCoins(int coins) -> Uncollect(string collectible, int quantity, int playerNumber = 0), Example:
RemoveCoins(10) -> Uncollect('Coin', 10)
RemovePoints(10) -> Uncollect('Point', 10)

This collectibles could be stored in a dictionary of <string, float> to allow decimal values

What do you think?

**Comment by FlipWebApps** [comment]
I like the idea. Do you see gems working in a similar fashion to how coins work (a simple counter based approach), or more an inventory type system? Also do you see this being something associated with the player, per level or both?

Duplicating the coins functionality would be pretty straight forward. I like the idea of generic collectibles too, but would need to think a bit more about the best way to implement this so it fits in with the rest of the framework and things like messaging, display components and the like.

**Comment by rubengc** [comment]
A generic collectibles has a lot of uses, for example, on infinite runners you could store coins (collected in game), purchased gems and traveled distance

Other games could need other types of counters like enemies defeated, bronce/silver/gold coins, etc 

In a more advanced contest, you could reward your players with some gems if they collect a big amount of coins or traveled X meters, internally all means the same a quantity of X to unlock Y

About storing them there are some scenarios but I think allow to store in each one is the right way, This could work pyramidally (Add a coin to Player -> Add to level -> Add to World -> Add to Game) to meet how much coins a player gained per each one (other thing could be the biggest amount of moneys that he gains in a level, but I think this feature could go separately from this)

The amount of a player can use on purchases will be the amount of the game, this let us use this feature also on multiplayer games where only local player coins come to our game amount but let us to know how much got other players

**Comment by FlipWebApps** [comment]
Hi. Sorry for the delay - for some reason I didn't get a notification you had posted.

I think that I get what you need now and agree that it is a good idea. I have a couple of updates that I need to get implemented first (associated prefabs with game items + 3d selection menus), but can look into adding this after that.

As you mention, a first step is probably a collection of string / floats with add and remove methods. Are there other things that could be of use here (components etc...)?

**Comment by FlipWebApps** [comment]
If you take a look in the latest master branch at the updated GameItem configuration under \FlipWebApps\GameFramework\_Demo\GameStructure\Resources\GameStructure\Level.

Could something similar be the way forward for these collectibles?

**Comment by rubengc** [comment]
Nice! I will check it as soon as possible

**Comment by FlipWebApps** [comment]
Great - let me know what you think. I should also mention that the latest update introduces a few (unavoidable) breaking changes, especially if you have used the GameItemExtensions. I am working on going back documenting these so probably best holding off on using this version for anything 'production' for another week or so, so that I get chance to fully document and test things.

**Comment by rubengc** [comment]
I see your changes, Do you want to apply same workflow of unlockable items for collectibles right?

I like the idea to allow expand them from scripting, could cover basic and advanced needs (like inventory items)

v4-work PR is full of new possibilities for Game Framework :)

**Comment by FlipWebApps** [comment]
I am thinking something similar - there would be a couple of predefined ones - coins / score and then you could create your own similar to how the prefab ->custom option works. You could then have Collect and Uncollect methods like you mention in the first post. I guess each option could have the following settings:

**Configuration options:**
name - unique name for the item.
save - always, per session, per level, +...?
Use IAP - checkbox - could easily listen for purchases collectible.<name>.<amount>

**Other values:**
int - a counter (or should this be float?)

+ any others you can think of?

**Comment by rubengc** [comment]
Sounds really good

About the counter, floats are a more flexible way but thinking on coins/gems/points all of them are using integer values

Also is posible much situations open the possibility to store time/distance so probably keeping float as counter will be much right un my opinion

**Comment by FlipWebApps** [comment]
Hi,

I have had a bit of time to look into this. I have been thinking about making this into a more generic variables / attributes option. The following shows how this looks in the GameItem configuration (I need to clean and improve the editor). The idea is that you can setup any type of variable that you need. You can then access these through methods like GameItem.Variables.GetXxx(name) e.g. GameManager.Instance.Levels.Selected.Variables.GetInt('Gems').Value += 10;

![image](https://cloud.githubusercontent.com/assets/15124170/22706556/087337c0-ed70-11e6-99fa-c4febf88c9a8.png)

Would that meet the needs that you originally put forward?

**Comment by FlipWebApps** [comment]
Custom Counters (which in addition to the variables above) are now added in the latest 4.5 release that fulfill the above requirements so closing this request - hope that it meets your needs. 

There will come additional components e.g. ShowCounterIcons and actions in EnableDisableGameObject that work with these in the next release to extend the concept even further
