### ISSUE TITLE
Namespaces improvements

### ISSUE THREAD

**Issue by rubengc** [FlipWebApps/GameFramework#21]
I have two recommendations to reduce and improve namespaces

1 - Remove FlipWebApps to bring more singularity to GameFramework
2 -  Remove Scripts, C# namespaces are used in other scripts to call GF scripts, It do not make sense to add scripts in all namespaces because there will not be other types of namespaces (for example we never will need GameFramework.Prefabs.UI)

Example of new namespaces:

```
using FlipWebApps.GameFramework.Scripts.GameStructure.Levels.ObjectModel;
using FlipWebApps.GameFramework.Scripts.UI.Other.Components.AbstractClasses;
```

```
using GameFramework.GameStructure.Levels.ObjectModel;
using GameFramework.UI.Other.Components.AbstractClasses;
```

**Comment by FlipWebApps** [comment]
Thanks for the suggestion. 

I like the idea and it in theory is nothing more than a simple search replace so should be pretty easy to implement. The only issue is that it will break all documentation links to the auto generated API and require users to do a similar search replace in their code. I will keep this open but probably make the change as part of a future v4.0 update

**Comment by rubengc** [comment]
Nice!

Let me know when do you want this changes and i can do It for you

**Comment by FlipWebApps** [comment]
Done as a part of the upcoming v4 release. Changes are in the main branch however this should still be considered experimental due the the scope of the changes for v4.

Thanks for the offer to do this, but was easiest to just do a simple search replace whilst I was working on some of the other changes - there are also some other bits I need to look into at the same time.
