### ISSUE TITLE
A way to pause level

### ISSUE THREAD

**Issue by rubengc** [FlipWebApps/GameFramework#23]
I noticed LevelManager.IsLevelRunning is protected on set and GameManage.IsPaused is deprecated

So, where is the current way to pause game through game framework?

**Comment by FlipWebApps** [comment]
IsLevelRunning is just a flag to know whether the current level is running - the LevelStarted and LevelFinished methods can be called to 'start' and 'finish' a level although this can be done automaticlly if you include the LevelManager script. The flag is protected as setting it would be confusing based upon the different states (e.g. not started, paused, completed) 

Gamemanager.IsPaused was just a flag that I included a long time ago for a game I made, but I was unsure of the best way to include this in the public framework hence it was marked as obsolete to avoid future issues. One option is to include this as a feature in LevelManager by just adding a bool flag and methods PauseLevel() / ResumeLevel().

My only hesitation is whether this should be on LevelManager or GameManager, although as the rest is on LevelManager perhaps to keep it there - I guess that is only in game you will need such pause functionality (you don't pause a menu). Not sure your thoughts on this based upon your game?

**Comment by rubengc** [comment]
To make It work I am changing isLevelFinished value but the right way is the use of Pause/Resume methods and they should affect to isLevelRunning 

Probably a new variable in LavelManager to know If game isPause could be useful for others purposes

**Comment by FlipWebApps** [comment]
If you take a look at the untested change I just posted (LevelManager.cs). This adds to LevelManager Pause() and Resume() methods and an IsLevelPaused flag. You can hook PauseLevel() directly up to a button click handler.

I added in a showPauseDialog parameter that I am thinking could automatically show a Pause window with Exit, Retry and Resume options. What do you think?

**Comment by rubengc** [comment]
I think LevelManager is almost complete with this methods (I am using asset store version so I not tested current changes but I am revising commit changes)

About a pause dialog could be to allow display some settings while game is paused

In other games I see a component like "watch a video to unlock a power up" that could be a really attractive feature to keep in mind

My current setup is I am using the settings dialog as pause menu (with exit, restart and resume buttons)

Something like that with a prize button could be a complete solution for a lot of games

**Comment by FlipWebApps** [comment]
Closing this as the above methods and flags are now included in the latest code including a new pause window with optional restart, resume, exit, quit and options entries (showcased in the updated demo). This should make it's way onto the asset store in about a weeks time (notice the important update comments if you upgrade). Adding custom controls to the pause window should be a simple case of modifying the prefab and / or subclassing the new PauseWindow class and overriding any methods to do setup.

It might make sense to optionally add basic options such as volume controls to this window too, but I don't think I would want to reproduce all options here (especially given there is a button you can include for this). The downside of adding such things here is that a user might then not use or realise about other more complete options in the separate settings window (language, restore purchases, custom options etc.).

If you have any improvements that you feel should be included though then please open a new issue and let me know :)
